services:

  db:
    image: postgres:15
    container_name: review_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews_db
    ports:
      - "5432:5432"
    volumes:
      - review_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: review_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/reviews_db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: review_frontend
    restart: always
    ports:
      - "5173:80"

volumes:
  review_pgdata:
